accounts:
  - name: alice
    coins: ["100000000ugecko", "10000000000000000000uMGT"]
  - name: bob
    coins: ["5000000000000ugecko"]
validator:
  name: alice
  staked: "100000000000000000000ugecko"
faucet:
  name: bob 
  coins: ["10ugecko"]
build:
  binary: "geckod"
init:
  home: "$HOME/.geckod"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "FCO_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "ugecko"
    mint:
      params:
        mint_denom: "ugecko"
    crisis:
      constant_fee:
        denom: "ugecko"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "ugecko"
    evm:
      params:
        evm_denom: "ugecko"
